// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/Person.proto

package com.leolee.protobuf;

public final class DataInfo2 {
  private DataInfo2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.DataPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
     * @return Whether the packageType field is set.
     */
    boolean hasPackageType();
    /**
     * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
     * @return The packageType.
     */
    com.leolee.protobuf.DataInfo2.DataPackage.PackageType getPackageType();

    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     * @return Whether the sudent field is set.
     */
    boolean hasSudent();
    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     * @return The sudent.
     */
    com.leolee.protobuf.DataInfo2.Student getSudent();
    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     */
    com.leolee.protobuf.DataInfo2.StudentOrBuilder getSudentOrBuilder();

    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     * @return Whether the dog field is set.
     */
    boolean hasDog();
    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     * @return The dog.
     */
    com.leolee.protobuf.DataInfo2.Dog getDog();
    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     */
    com.leolee.protobuf.DataInfo2.DogOrBuilder getDogOrBuilder();

    public com.leolee.protobuf.DataInfo2.DataPackage.PackageCase getPackageCase();
  }
  /**
   * <pre>
   *----------------多message的根节点
   * </pre>
   *
   * Protobuf type {@code com.leolee.protobuf.DataPackage}
   */
  public static final class DataPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.leolee.protobuf.DataPackage)
      DataPackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPackage.newBuilder() to construct.
    private DataPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPackage() {
      packageType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPackage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.leolee.protobuf.DataInfo2.DataPackage.PackageType value = com.leolee.protobuf.DataInfo2.DataPackage.PackageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                packageType_ = rawValue;
              }
              break;
            }
            case 18: {
              com.leolee.protobuf.DataInfo2.Student.Builder subBuilder = null;
              if (packageCase_ == 2) {
                subBuilder = ((com.leolee.protobuf.DataInfo2.Student) package_).toBuilder();
              }
              package_ =
                  input.readMessage(com.leolee.protobuf.DataInfo2.Student.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leolee.protobuf.DataInfo2.Student) package_);
                package_ = subBuilder.buildPartial();
              }
              packageCase_ = 2;
              break;
            }
            case 26: {
              com.leolee.protobuf.DataInfo2.Dog.Builder subBuilder = null;
              if (packageCase_ == 3) {
                subBuilder = ((com.leolee.protobuf.DataInfo2.Dog) package_).toBuilder();
              }
              package_ =
                  input.readMessage(com.leolee.protobuf.DataInfo2.Dog.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.leolee.protobuf.DataInfo2.Dog) package_);
                package_ = subBuilder.buildPartial();
              }
              packageCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_DataPackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_DataPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leolee.protobuf.DataInfo2.DataPackage.class, com.leolee.protobuf.DataInfo2.DataPackage.Builder.class);
    }

    /**
     * <pre>
     *数据包类型
     * </pre>
     *
     * Protobuf enum {@code com.leolee.protobuf.DataPackage.PackageType}
     */
    public enum PackageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STUDENT = 0;</code>
       */
      STUDENT(0),
      /**
       * <code>DOG = 1;</code>
       */
      DOG(1),
      ;

      /**
       * <code>STUDENT = 0;</code>
       */
      public static final int STUDENT_VALUE = 0;
      /**
       * <code>DOG = 1;</code>
       */
      public static final int DOG_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PackageType forNumber(int value) {
        switch (value) {
          case 0: return STUDENT;
          case 1: return DOG;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PackageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PackageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PackageType>() {
              public PackageType findValueByNumber(int number) {
                return PackageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.leolee.protobuf.DataInfo2.DataPackage.getDescriptor().getEnumTypes().get(0);
      }

      private static final PackageType[] VALUES = values();

      public static PackageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PackageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.leolee.protobuf.DataPackage.PackageType)
    }

    private int bitField0_;
    private int packageCase_ = 0;
    private java.lang.Object package_;
    public enum PackageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      SUDENT(2),
      DOG(3),
      PACKAGE_NOT_SET(0);
      private final int value;
      private PackageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackageCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackageCase forNumber(int value) {
        switch (value) {
          case 2: return SUDENT;
          case 3: return DOG;
          case 0: return PACKAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackageCase
    getPackageCase() {
      return PackageCase.forNumber(
          packageCase_);
    }

    public static final int PACKAGE_TYPE_FIELD_NUMBER = 1;
    private int packageType_;
    /**
     * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
     * @return Whether the packageType field is set.
     */
    @java.lang.Override public boolean hasPackageType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
     * @return The packageType.
     */
    @java.lang.Override public com.leolee.protobuf.DataInfo2.DataPackage.PackageType getPackageType() {
      @SuppressWarnings("deprecation")
      com.leolee.protobuf.DataInfo2.DataPackage.PackageType result = com.leolee.protobuf.DataInfo2.DataPackage.PackageType.valueOf(packageType_);
      return result == null ? com.leolee.protobuf.DataInfo2.DataPackage.PackageType.STUDENT : result;
    }

    public static final int SUDENT_FIELD_NUMBER = 2;
    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     * @return Whether the sudent field is set.
     */
    @java.lang.Override
    public boolean hasSudent() {
      return packageCase_ == 2;
    }
    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     * @return The sudent.
     */
    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.Student getSudent() {
      if (packageCase_ == 2) {
         return (com.leolee.protobuf.DataInfo2.Student) package_;
      }
      return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
    }
    /**
     * <code>.com.leolee.protobuf.Student sudent = 2;</code>
     */
    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.StudentOrBuilder getSudentOrBuilder() {
      if (packageCase_ == 2) {
         return (com.leolee.protobuf.DataInfo2.Student) package_;
      }
      return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
    }

    public static final int DOG_FIELD_NUMBER = 3;
    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     * @return Whether the dog field is set.
     */
    @java.lang.Override
    public boolean hasDog() {
      return packageCase_ == 3;
    }
    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     * @return The dog.
     */
    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.Dog getDog() {
      if (packageCase_ == 3) {
         return (com.leolee.protobuf.DataInfo2.Dog) package_;
      }
      return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
    }
    /**
     * <code>.com.leolee.protobuf.Dog dog = 3;</code>
     */
    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.DogOrBuilder getDogOrBuilder() {
      if (packageCase_ == 3) {
         return (com.leolee.protobuf.DataInfo2.Dog) package_;
      }
      return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPackageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, packageType_);
      }
      if (packageCase_ == 2) {
        output.writeMessage(2, (com.leolee.protobuf.DataInfo2.Student) package_);
      }
      if (packageCase_ == 3) {
        output.writeMessage(3, (com.leolee.protobuf.DataInfo2.Dog) package_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, packageType_);
      }
      if (packageCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.leolee.protobuf.DataInfo2.Student) package_);
      }
      if (packageCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.leolee.protobuf.DataInfo2.Dog) package_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leolee.protobuf.DataInfo2.DataPackage)) {
        return super.equals(obj);
      }
      com.leolee.protobuf.DataInfo2.DataPackage other = (com.leolee.protobuf.DataInfo2.DataPackage) obj;

      if (hasPackageType() != other.hasPackageType()) return false;
      if (hasPackageType()) {
        if (packageType_ != other.packageType_) return false;
      }
      if (!getPackageCase().equals(other.getPackageCase())) return false;
      switch (packageCase_) {
        case 2:
          if (!getSudent()
              .equals(other.getSudent())) return false;
          break;
        case 3:
          if (!getDog()
              .equals(other.getDog())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPackageType()) {
        hash = (37 * hash) + PACKAGE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + packageType_;
      }
      switch (packageCase_) {
        case 2:
          hash = (37 * hash) + SUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getSudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + DOG_FIELD_NUMBER;
          hash = (53 * hash) + getDog().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.DataPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leolee.protobuf.DataInfo2.DataPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *----------------多message的根节点
     * </pre>
     *
     * Protobuf type {@code com.leolee.protobuf.DataPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.leolee.protobuf.DataPackage)
        com.leolee.protobuf.DataInfo2.DataPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_DataPackage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_DataPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leolee.protobuf.DataInfo2.DataPackage.class, com.leolee.protobuf.DataInfo2.DataPackage.Builder.class);
      }

      // Construct using com.leolee.protobuf.DataInfo2.DataPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        packageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        packageCase_ = 0;
        package_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_DataPackage_descriptor;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.DataPackage getDefaultInstanceForType() {
        return com.leolee.protobuf.DataInfo2.DataPackage.getDefaultInstance();
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.DataPackage build() {
        com.leolee.protobuf.DataInfo2.DataPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.DataPackage buildPartial() {
        com.leolee.protobuf.DataInfo2.DataPackage result = new com.leolee.protobuf.DataInfo2.DataPackage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageType_ = packageType_;
        if (packageCase_ == 2) {
          if (sudentBuilder_ == null) {
            result.package_ = package_;
          } else {
            result.package_ = sudentBuilder_.build();
          }
        }
        if (packageCase_ == 3) {
          if (dogBuilder_ == null) {
            result.package_ = package_;
          } else {
            result.package_ = dogBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.packageCase_ = packageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leolee.protobuf.DataInfo2.DataPackage) {
          return mergeFrom((com.leolee.protobuf.DataInfo2.DataPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leolee.protobuf.DataInfo2.DataPackage other) {
        if (other == com.leolee.protobuf.DataInfo2.DataPackage.getDefaultInstance()) return this;
        if (other.hasPackageType()) {
          setPackageType(other.getPackageType());
        }
        switch (other.getPackageCase()) {
          case SUDENT: {
            mergeSudent(other.getSudent());
            break;
          }
          case DOG: {
            mergeDog(other.getDog());
            break;
          }
          case PACKAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPackageType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leolee.protobuf.DataInfo2.DataPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leolee.protobuf.DataInfo2.DataPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packageCase_ = 0;
      private java.lang.Object package_;
      public PackageCase
          getPackageCase() {
        return PackageCase.forNumber(
            packageCase_);
      }

      public Builder clearPackage() {
        packageCase_ = 0;
        package_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int packageType_ = 0;
      /**
       * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
       * @return Whether the packageType field is set.
       */
      @java.lang.Override public boolean hasPackageType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
       * @return The packageType.
       */
      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.DataPackage.PackageType getPackageType() {
        @SuppressWarnings("deprecation")
        com.leolee.protobuf.DataInfo2.DataPackage.PackageType result = com.leolee.protobuf.DataInfo2.DataPackage.PackageType.valueOf(packageType_);
        return result == null ? com.leolee.protobuf.DataInfo2.DataPackage.PackageType.STUDENT : result;
      }
      /**
       * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
       * @param value The packageType to set.
       * @return This builder for chaining.
       */
      public Builder setPackageType(com.leolee.protobuf.DataInfo2.DataPackage.PackageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        packageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.leolee.protobuf.DataPackage.PackageType package_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leolee.protobuf.DataInfo2.Student, com.leolee.protobuf.DataInfo2.Student.Builder, com.leolee.protobuf.DataInfo2.StudentOrBuilder> sudentBuilder_;
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       * @return Whether the sudent field is set.
       */
      @java.lang.Override
      public boolean hasSudent() {
        return packageCase_ == 2;
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       * @return The sudent.
       */
      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Student getSudent() {
        if (sudentBuilder_ == null) {
          if (packageCase_ == 2) {
            return (com.leolee.protobuf.DataInfo2.Student) package_;
          }
          return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
        } else {
          if (packageCase_ == 2) {
            return sudentBuilder_.getMessage();
          }
          return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      public Builder setSudent(com.leolee.protobuf.DataInfo2.Student value) {
        if (sudentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          package_ = value;
          onChanged();
        } else {
          sudentBuilder_.setMessage(value);
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      public Builder setSudent(
          com.leolee.protobuf.DataInfo2.Student.Builder builderForValue) {
        if (sudentBuilder_ == null) {
          package_ = builderForValue.build();
          onChanged();
        } else {
          sudentBuilder_.setMessage(builderForValue.build());
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      public Builder mergeSudent(com.leolee.protobuf.DataInfo2.Student value) {
        if (sudentBuilder_ == null) {
          if (packageCase_ == 2 &&
              package_ != com.leolee.protobuf.DataInfo2.Student.getDefaultInstance()) {
            package_ = com.leolee.protobuf.DataInfo2.Student.newBuilder((com.leolee.protobuf.DataInfo2.Student) package_)
                .mergeFrom(value).buildPartial();
          } else {
            package_ = value;
          }
          onChanged();
        } else {
          if (packageCase_ == 2) {
            sudentBuilder_.mergeFrom(value);
          }
          sudentBuilder_.setMessage(value);
        }
        packageCase_ = 2;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      public Builder clearSudent() {
        if (sudentBuilder_ == null) {
          if (packageCase_ == 2) {
            packageCase_ = 0;
            package_ = null;
            onChanged();
          }
        } else {
          if (packageCase_ == 2) {
            packageCase_ = 0;
            package_ = null;
          }
          sudentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      public com.leolee.protobuf.DataInfo2.Student.Builder getSudentBuilder() {
        return getSudentFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.StudentOrBuilder getSudentOrBuilder() {
        if ((packageCase_ == 2) && (sudentBuilder_ != null)) {
          return sudentBuilder_.getMessageOrBuilder();
        } else {
          if (packageCase_ == 2) {
            return (com.leolee.protobuf.DataInfo2.Student) package_;
          }
          return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.com.leolee.protobuf.Student sudent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leolee.protobuf.DataInfo2.Student, com.leolee.protobuf.DataInfo2.Student.Builder, com.leolee.protobuf.DataInfo2.StudentOrBuilder> 
          getSudentFieldBuilder() {
        if (sudentBuilder_ == null) {
          if (!(packageCase_ == 2)) {
            package_ = com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
          }
          sudentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leolee.protobuf.DataInfo2.Student, com.leolee.protobuf.DataInfo2.Student.Builder, com.leolee.protobuf.DataInfo2.StudentOrBuilder>(
                  (com.leolee.protobuf.DataInfo2.Student) package_,
                  getParentForChildren(),
                  isClean());
          package_ = null;
        }
        packageCase_ = 2;
        onChanged();;
        return sudentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.leolee.protobuf.DataInfo2.Dog, com.leolee.protobuf.DataInfo2.Dog.Builder, com.leolee.protobuf.DataInfo2.DogOrBuilder> dogBuilder_;
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       * @return Whether the dog field is set.
       */
      @java.lang.Override
      public boolean hasDog() {
        return packageCase_ == 3;
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       * @return The dog.
       */
      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Dog getDog() {
        if (dogBuilder_ == null) {
          if (packageCase_ == 3) {
            return (com.leolee.protobuf.DataInfo2.Dog) package_;
          }
          return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
        } else {
          if (packageCase_ == 3) {
            return dogBuilder_.getMessage();
          }
          return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
        }
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      public Builder setDog(com.leolee.protobuf.DataInfo2.Dog value) {
        if (dogBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          package_ = value;
          onChanged();
        } else {
          dogBuilder_.setMessage(value);
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      public Builder setDog(
          com.leolee.protobuf.DataInfo2.Dog.Builder builderForValue) {
        if (dogBuilder_ == null) {
          package_ = builderForValue.build();
          onChanged();
        } else {
          dogBuilder_.setMessage(builderForValue.build());
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      public Builder mergeDog(com.leolee.protobuf.DataInfo2.Dog value) {
        if (dogBuilder_ == null) {
          if (packageCase_ == 3 &&
              package_ != com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance()) {
            package_ = com.leolee.protobuf.DataInfo2.Dog.newBuilder((com.leolee.protobuf.DataInfo2.Dog) package_)
                .mergeFrom(value).buildPartial();
          } else {
            package_ = value;
          }
          onChanged();
        } else {
          if (packageCase_ == 3) {
            dogBuilder_.mergeFrom(value);
          }
          dogBuilder_.setMessage(value);
        }
        packageCase_ = 3;
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      public Builder clearDog() {
        if (dogBuilder_ == null) {
          if (packageCase_ == 3) {
            packageCase_ = 0;
            package_ = null;
            onChanged();
          }
        } else {
          if (packageCase_ == 3) {
            packageCase_ = 0;
            package_ = null;
          }
          dogBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      public com.leolee.protobuf.DataInfo2.Dog.Builder getDogBuilder() {
        return getDogFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.DogOrBuilder getDogOrBuilder() {
        if ((packageCase_ == 3) && (dogBuilder_ != null)) {
          return dogBuilder_.getMessageOrBuilder();
        } else {
          if (packageCase_ == 3) {
            return (com.leolee.protobuf.DataInfo2.Dog) package_;
          }
          return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
        }
      }
      /**
       * <code>.com.leolee.protobuf.Dog dog = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.leolee.protobuf.DataInfo2.Dog, com.leolee.protobuf.DataInfo2.Dog.Builder, com.leolee.protobuf.DataInfo2.DogOrBuilder> 
          getDogFieldBuilder() {
        if (dogBuilder_ == null) {
          if (!(packageCase_ == 3)) {
            package_ = com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
          }
          dogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.leolee.protobuf.DataInfo2.Dog, com.leolee.protobuf.DataInfo2.Dog.Builder, com.leolee.protobuf.DataInfo2.DogOrBuilder>(
                  (com.leolee.protobuf.DataInfo2.Dog) package_,
                  getParentForChildren(),
                  isClean());
          package_ = null;
        }
        packageCase_ = 3;
        onChanged();;
        return dogBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.leolee.protobuf.DataPackage)
    }

    // @@protoc_insertion_point(class_scope:com.leolee.protobuf.DataPackage)
    private static final com.leolee.protobuf.DataInfo2.DataPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leolee.protobuf.DataInfo2.DataPackage();
    }

    public static com.leolee.protobuf.DataInfo2.DataPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataPackage>
        PARSER = new com.google.protobuf.AbstractParser<DataPackage>() {
      @java.lang.Override
      public DataPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPackage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.DataPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * <pre>
   *----------------多message
   * </pre>
   *
   * Protobuf type {@code com.leolee.protobuf.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.leolee.protobuf.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              address_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leolee.protobuf.DataInfo2.Student.class, com.leolee.protobuf.DataInfo2.Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>optional int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 3;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leolee.protobuf.DataInfo2.Student)) {
        return super.equals(obj);
      }
      com.leolee.protobuf.DataInfo2.Student other = (com.leolee.protobuf.DataInfo2.Student) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leolee.protobuf.DataInfo2.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *----------------多message
     * </pre>
     *
     * Protobuf type {@code com.leolee.protobuf.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.leolee.protobuf.Student)
        com.leolee.protobuf.DataInfo2.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leolee.protobuf.DataInfo2.Student.class, com.leolee.protobuf.DataInfo2.Student.Builder.class);
      }

      // Construct using com.leolee.protobuf.DataInfo2.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Student_descriptor;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Student getDefaultInstanceForType() {
        return com.leolee.protobuf.DataInfo2.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Student build() {
        com.leolee.protobuf.DataInfo2.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Student buildPartial() {
        com.leolee.protobuf.DataInfo2.Student result = new com.leolee.protobuf.DataInfo2.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leolee.protobuf.DataInfo2.Student) {
          return mergeFrom((com.leolee.protobuf.DataInfo2.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leolee.protobuf.DataInfo2.Student other) {
        if (other == com.leolee.protobuf.DataInfo2.Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000004;
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leolee.protobuf.DataInfo2.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leolee.protobuf.DataInfo2.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 3;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.leolee.protobuf.Student)
    }

    // @@protoc_insertion_point(class_scope:com.leolee.protobuf.Student)
    private static final com.leolee.protobuf.DataInfo2.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leolee.protobuf.DataInfo2.Student();
    }

    public static com.leolee.protobuf.DataInfo2.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.Dog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string dog_name = 1;</code>
     * @return Whether the dogName field is set.
     */
    boolean hasDogName();
    /**
     * <code>optional string dog_name = 1;</code>
     * @return The dogName.
     */
    java.lang.String getDogName();
    /**
     * <code>optional string dog_name = 1;</code>
     * @return The bytes for dogName.
     */
    com.google.protobuf.ByteString
        getDogNameBytes();

    /**
     * <code>optional int32 dog_age = 2;</code>
     * @return Whether the dogAge field is set.
     */
    boolean hasDogAge();
    /**
     * <code>optional int32 dog_age = 2;</code>
     * @return The dogAge.
     */
    int getDogAge();
  }
  /**
   * Protobuf type {@code com.leolee.protobuf.Dog}
   */
  public static final class Dog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.leolee.protobuf.Dog)
      DogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dog.newBuilder() to construct.
    private Dog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dog() {
      dogName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              dogName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dogAge_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Dog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Dog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leolee.protobuf.DataInfo2.Dog.class, com.leolee.protobuf.DataInfo2.Dog.Builder.class);
    }

    private int bitField0_;
    public static final int DOG_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object dogName_;
    /**
     * <code>optional string dog_name = 1;</code>
     * @return Whether the dogName field is set.
     */
    @java.lang.Override
    public boolean hasDogName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string dog_name = 1;</code>
     * @return The dogName.
     */
    @java.lang.Override
    public java.lang.String getDogName() {
      java.lang.Object ref = dogName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dogName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dog_name = 1;</code>
     * @return The bytes for dogName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDogNameBytes() {
      java.lang.Object ref = dogName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dogName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOG_AGE_FIELD_NUMBER = 2;
    private int dogAge_;
    /**
     * <code>optional int32 dog_age = 2;</code>
     * @return Whether the dogAge field is set.
     */
    @java.lang.Override
    public boolean hasDogAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 dog_age = 2;</code>
     * @return The dogAge.
     */
    @java.lang.Override
    public int getDogAge() {
      return dogAge_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dogName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, dogAge_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dogName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dogAge_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.leolee.protobuf.DataInfo2.Dog)) {
        return super.equals(obj);
      }
      com.leolee.protobuf.DataInfo2.Dog other = (com.leolee.protobuf.DataInfo2.Dog) obj;

      if (hasDogName() != other.hasDogName()) return false;
      if (hasDogName()) {
        if (!getDogName()
            .equals(other.getDogName())) return false;
      }
      if (hasDogAge() != other.hasDogAge()) return false;
      if (hasDogAge()) {
        if (getDogAge()
            != other.getDogAge()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDogName()) {
        hash = (37 * hash) + DOG_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDogName().hashCode();
      }
      if (hasDogAge()) {
        hash = (37 * hash) + DOG_AGE_FIELD_NUMBER;
        hash = (53 * hash) + getDogAge();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.leolee.protobuf.DataInfo2.Dog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.leolee.protobuf.DataInfo2.Dog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.leolee.protobuf.Dog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.leolee.protobuf.Dog)
        com.leolee.protobuf.DataInfo2.DogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Dog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Dog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.leolee.protobuf.DataInfo2.Dog.class, com.leolee.protobuf.DataInfo2.Dog.Builder.class);
      }

      // Construct using com.leolee.protobuf.DataInfo2.Dog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dogName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        dogAge_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.leolee.protobuf.DataInfo2.internal_static_com_leolee_protobuf_Dog_descriptor;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Dog getDefaultInstanceForType() {
        return com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance();
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Dog build() {
        com.leolee.protobuf.DataInfo2.Dog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.leolee.protobuf.DataInfo2.Dog buildPartial() {
        com.leolee.protobuf.DataInfo2.Dog result = new com.leolee.protobuf.DataInfo2.Dog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dogName_ = dogName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dogAge_ = dogAge_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.leolee.protobuf.DataInfo2.Dog) {
          return mergeFrom((com.leolee.protobuf.DataInfo2.Dog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.leolee.protobuf.DataInfo2.Dog other) {
        if (other == com.leolee.protobuf.DataInfo2.Dog.getDefaultInstance()) return this;
        if (other.hasDogName()) {
          bitField0_ |= 0x00000001;
          dogName_ = other.dogName_;
          onChanged();
        }
        if (other.hasDogAge()) {
          setDogAge(other.getDogAge());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.leolee.protobuf.DataInfo2.Dog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.leolee.protobuf.DataInfo2.Dog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object dogName_ = "";
      /**
       * <code>optional string dog_name = 1;</code>
       * @return Whether the dogName field is set.
       */
      public boolean hasDogName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string dog_name = 1;</code>
       * @return The dogName.
       */
      public java.lang.String getDogName() {
        java.lang.Object ref = dogName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dogName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dog_name = 1;</code>
       * @return The bytes for dogName.
       */
      public com.google.protobuf.ByteString
          getDogNameBytes() {
        java.lang.Object ref = dogName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dogName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dog_name = 1;</code>
       * @param value The dogName to set.
       * @return This builder for chaining.
       */
      public Builder setDogName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dogName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dog_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDogName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dogName_ = getDefaultInstance().getDogName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dog_name = 1;</code>
       * @param value The bytes for dogName to set.
       * @return This builder for chaining.
       */
      public Builder setDogNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dogName_ = value;
        onChanged();
        return this;
      }

      private int dogAge_ ;
      /**
       * <code>optional int32 dog_age = 2;</code>
       * @return Whether the dogAge field is set.
       */
      @java.lang.Override
      public boolean hasDogAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 dog_age = 2;</code>
       * @return The dogAge.
       */
      @java.lang.Override
      public int getDogAge() {
        return dogAge_;
      }
      /**
       * <code>optional int32 dog_age = 2;</code>
       * @param value The dogAge to set.
       * @return This builder for chaining.
       */
      public Builder setDogAge(int value) {
        bitField0_ |= 0x00000002;
        dogAge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dog_age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDogAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dogAge_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.leolee.protobuf.Dog)
    }

    // @@protoc_insertion_point(class_scope:com.leolee.protobuf.Dog)
    private static final com.leolee.protobuf.DataInfo2.Dog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.leolee.protobuf.DataInfo2.Dog();
    }

    public static com.leolee.protobuf.DataInfo2.Dog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Dog>
        PARSER = new com.google.protobuf.AbstractParser<Dog>() {
      @java.lang.Override
      public Dog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.leolee.protobuf.DataInfo2.Dog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_leolee_protobuf_DataPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_leolee_protobuf_DataPackage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_leolee_protobuf_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_leolee_protobuf_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_leolee_protobuf_Dog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_leolee_protobuf_Dog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031src/protobuf/Person.proto\022\023com.leolee." +
      "protobuf\"\332\001\n\013DataPackage\022B\n\014package_type" +
      "\030\001 \002(\0162,.com.leolee.protobuf.DataPackage" +
      ".PackageType\022.\n\006sudent\030\002 \001(\0132\034.com.leole" +
      "e.protobuf.StudentH\000\022\'\n\003dog\030\003 \001(\0132\030.com." +
      "leolee.protobuf.DogH\000\"#\n\013PackageType\022\013\n\007" +
      "STUDENT\020\000\022\007\n\003DOG\020\001B\t\n\007Package\"5\n\007Student" +
      "\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\017\n\007address\030\003" +
      " \001(\t\"(\n\003Dog\022\020\n\010dog_name\030\001 \001(\t\022\017\n\007dog_age" +
      "\030\002 \001(\005B\"\n\023com.leolee.protobufB\tDataInfo2" +
      "H\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_leolee_protobuf_DataPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_leolee_protobuf_DataPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_leolee_protobuf_DataPackage_descriptor,
        new java.lang.String[] { "PackageType", "Sudent", "Dog", "Package", });
    internal_static_com_leolee_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_leolee_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_leolee_protobuf_Student_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_com_leolee_protobuf_Dog_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_leolee_protobuf_Dog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_leolee_protobuf_Dog_descriptor,
        new java.lang.String[] { "DogName", "DogAge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
