// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCStudent.proto

package com.leolee.protobuf.gRPC.Student;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
