// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCStudent.proto

package com.leolee.protobuf.gRPC.Student;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   * @return The realName.
   */
  String getRealName();
  /**
   * <code>string realName = 1;</code>
   * @return The bytes for realName.
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
