// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCStudent.proto

package com.leolee.protobuf.gRPC.Student;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   * @return The responseInfo.
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   * @return The bytes for responseInfo.
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
