// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCStudent.proto

package com.leolee.protobuf.gRPC.Student;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.leolee.protobuf.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.leolee.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.leolee.protobuf.gRPC.Student.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.leolee.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.leolee.protobuf.gRPC.Student.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.leolee.protobuf.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.leolee.protobuf.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.leolee.protobuf.gRPC.Student.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.leolee.protobuf.StudentResponse studentResponse = 1;</code>
   */
  com.leolee.protobuf.gRPC.Student.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
