// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPCStudent.proto

package com.leolee.protobuf.gRPC.Student;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_leolee_protobuf_MyRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_leolee_protobuf_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_leolee_protobuf_MyResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_leolee_protobuf_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021gRPCStudent.proto\022\023com.leolee.protobuf" +
      "\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyRes" +
      "ponse\022\020\n\010realName\030\001 \001(\t2l\n\016StudentServic" +
      "e\022Z\n\025GetRealNameByUserName\022\036.com.leolee." +
      "protobuf.MyRequest\032\037.com.leolee.protobuf" +
      ".MyResponse\"\000B2\n com.leolee.protobuf.gRP" +
      "C.StudentB\014StudentProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_leolee_protobuf_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_leolee_protobuf_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_leolee_protobuf_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_leolee_protobuf_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_leolee_protobuf_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_leolee_protobuf_MyResponse_descriptor,
        new String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
